[project]
name = "gravitationalsimulator2-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numba>=0.62.1",
    "numpy>=2.3.5",
    "py-spy>=0.4.1",
    "pygame>=2.6.1",
]
